name: first workflow

on:
  workflow_dispatch:

env: 
  App_name: roboshop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello this is my first script
        run: echo "Hello from GitHub Actions"

      - name: printing date,hostname
        run: |
          pwd
          hostname
          whoami

      - name: using env
        run: echo $App_name
      
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: testing need
        run: echo "testing is working successfully"

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: running this from second job
        run: echo "from second job"
  
  Github_context:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: printing context
        run: echo " ${{ toJson(github) }}"
  
  job_context:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: printing context
        run: echo " ${{ toJson(job) }}"

  runner_context:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: printing context
        run: echo " ${{ toJson(github) }}"